version: 2

common: &common
  docker:
    - image: neomake/vims-for-tests:32@sha256:8bea15fee56cb499c6c94203018f00f834d36576f56122f03dac76c98c9d8b9e
  working_directory: ~/repo
  steps:
    - checkout
    - run: make --keep-going testcoverage TEST_VIM=$TEST_VIM _SED_HIGHLIGHT_ERRORS='| contrib/highlight-log vader'
    - run:
        name: Upload coverage results
        command: |
          set -x
          coverage report -m --skip-covered
          coverage xml
          # -Z: exit with 1 in case of failures.
          codecov -Z -X search -X gcov -X pycov -f coverage.xml \
            -n "$CIRCLE_JOB" -F ${CIRCLE_JOB%%-*},${CIRCLE_JOB//[-.]/}
          set +x
jobs:
  nvim-031:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.3.1
  nvim-017:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.1.7
  vim-81:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim81
  vim-80:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim80
  vim-74-xenial:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-xenial
  vim-74-trusty:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-trusty
  vim-73:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim73

  checkqa:
    <<: *common
    environment:
      VIMHELPLINT_VIM=/vim-build/bin/vim81
    steps:
      - checkout
      - run:
          name: Checks
          command: |
            set -x
            python -m ensurepip --user
            PATH=$HOME/.local/bin:$PATH
            pip3 install --user -U 'vim-vint>=0.4a1'
            vint --version
            make --keep-going check check_docker check_lint_diff vint
            set +x

workflows:
  version: 2
  test:
    jobs:
      - checkqa
